linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain
  gosec:
    excludes:
      - G402
      - G404
  revive:
    rules:
      - name: var-declaration
        disabled: true

linters:
  enable-all: true
  disable:
    - prealloc
    - lll
    - dupl
    - funlen
    - wsl
    - unparam
    - err113
    - nestif
    - errcheck
    - wrapcheck
    - varnamelen
    - tagliatelle
    - gomoddirectives
    - ireturn
    - nlreturn
    - cyclop
    - errorlint
    - noctx
    - gocognit
    - gosec
    - exportloopref
    - stylecheck
    - exhaustruct
    - gci
    - depguard
    - goimports
    - mnd
    - perfsprint
    - testpackage
    - interfacebloat
    - dupword
    - godox
