 # Log level. Defaults to "info"
log_level: info
 # Output logs as JSON. Useful if you are using logging aggregation solutions such as ELK. Defaults to false.
json: false
telegram:
  # Telegram bot token, you can create a Telegam bot with @BotFather bot on Telegram
  token: xxx:yyy
  # List of Telegram user IDs who can interact with the bot.
  # You can get your id with @getmyid_bot on Telegram.
  # If not provided, anyone can access this bot, so it's not recommended skipping it.
  admins: [1, 2]
grafana:
  # URL of the remote Grafana to do queries against.
  url: http://localhost:3000
   # Grafana credentials.
  user: admin
  password: admin
  # Timezone for rendering graphs
  timezone: Europe/Moscow
# Optional config if you use external Alertmanager, used for getting silences list and creating new ones.
alertmanager:
  # URL of the remote Grafana to do queries against. Defaults to http://localhost:9093
  url: http://localhost:9093
  # Alertmanager credentials
  user: admin
  password: admin
