# Timezone. Used when displaying dates (like in silences and alerts).
# Defaults to "Etc/GMT" (so GMT+0)
timezone: "Europe/Moscow"
# Logging configuration.
log:
  # Log level. Defaults to "info"
  level: info
 # Output logs as JSON. Useful if you are using logging aggregation solutions such as ELK. Defaults to false.
  json: false
# Telegram bot token, you can create a Telegam bot with @BotFather bot on Telegram
telegram:
  token: xxx:yyy
  # List of Telegram user IDs who can interact with the bot.
  # You can get your id with @getmyid_bot on Telegram.
  # If not provided, anyone can access this bot, so it's not recommended skipping it.
  admins: [1, 2]
grafana:
  # URL of the remote Grafana to do queries against.
  url: http://localhost:3000
   # Grafana credentials. You can authorize either with login/password, as below...
  user: admin
  password: admin
  # ... or with bearer token.
  token: xxxxx
  # Default render options. If you want to avoid specifying render params each time,
  # you can specify it here, and it'll apply to all render requests, then all params you've specified
  # in your render request would be added above these.
  # Defaults to "orgId: 1, from: now, to: now-30m"
  # All params are expected to be strings, even if they are number, so put them in quotes.
  # Here's an example of how you can customize it:
  render_options:
    # Customize your time interval for rendering
    from: "now"
    to: "now-6h"
    # Customize your timezone
    timezone: "Europe/Moscow"
    # Customize your plot width/height
    width: "1000"
    height: "500"
# Optional config if you use external Alertmanager, used for getting silences list and creating new ones.
alertmanager:
  # URL of the remote Grafana to do queries against. Defaults to http://localhost:9093
  url: http://localhost:9093
  # Alertmanager credentials
  user: admin
  password: admin
