name: test
on: [push]
jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.23.0'
      - run: go version
      - run: go mod download
      - run: go build cmd/grafana-interacter.go
  go-vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.23.0'
      - run: go version
      - run: go mod download
      - run: go vet ./...
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: --timeout 300s
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Run tests
        run: go test -coverprofile coverage.txt -coverpkg ./... -v ./...
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.3.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: freak12techno/grafana-interacter